spring:
  profiles:
    active: test
  aop:
    proxy-target-class: true
    auto: true
  mvc:
    view:
      suffix: .html
      prefix: /WEB-INF/views/
    pathmatch:
      use-suffix-pattern: true
  http:
    encoding:
      charset: UTF-8
      force: true
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/views/
    mode: HTML
    servlet:
      content-type: text/html
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  global-config:
    db-config:
      table-prefix: plant_
    banner: false
  mapper-locations: classpath:mapper/*DAO.xml
  type-aliases-package: com.moguying.plant.core.entity
  configuration:
    map-underscore-to-camel-case: true
cache:
  default-ttl: 300 #默认缓存时长

logging:
  level:
    com.moguying: debug
  file: ./logs/plant-web.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

server:
  servlet:
    session:
      timeout: 1h

#短信相关
message:
  send:
    url: http://smssh1.253.com/msg/send/json
  account: N1600574
  sale:
    account: M6652821
  password: ABUt0xrFv3ad35
  time: 60000
  code: 【蘑菇营】您正在登录帐号，验证码code，1分钟内有效，为了您的帐号安全，请勿泄露给他人。如非本人操作，请致电客服：400-669-0808
  seed:
    reap: 【蘑菇营】亲爱的phone，您count份菌包已成长，已采摘完毕，可以去出售啦！
  withdraw:
    success: 【蘑菇营】您于time的提现申请审核通过，详情可登录app查看或咨询客服400-669-0808！
    fail: 【蘑菇营】您于time的提现申请审核被驳回，详情可登录app查看或咨询客服400-669-0808！
  mall:
    send: 【蘑菇营】您在商城购买产品已发货，详情可登录app查看或咨询客服400-669-0808！
  fertilizer:
    send: 【蘑菇营】恭喜您注册成功！蘑菇营为答谢您的支持，特奉上16元满减券，券已发放至你的账户中，请登录查收，开启趣味种植之旅~
#富文本添加图片自适应
meta:
  content:
    img: '<style>img{max-width:100%!important;}</style>'

#第三方支付公司配置
payment:
  merNo: '0009500'
  version: '1.1'
  signType: 'CFCA'
  callback: https://api.zymoguying.com/payment/notify
  pfxfile: classpath:Hyswkj2019.pfx
  cerfile: classpath:sq_formal_encrypt.cer
  password: Hyswkj2019
  return:
    url:

#邀请奖励比例
invite:
  rate: 0.0005

#提现规则
withdraw:
  min: 100.00
  max: 200000.00
  fee: 0.00
  daily:
    max: 1000000.00

#订单有效时长（秒）
order:
  expire:
    time: 300

#田园种植
farmer:
  energy:
    ok:
      ok: 86400
      min: 84600
      max: 127800
    lose: 129600
#邀请设置
user:
  invite:
    bg:
      image: classpath:/images/user_private_invite_bg.jpg
    icon: classpath:/images/invite_icon.png
    url: https://m.zymoguying.com/index/promote/invitecode/
#微信配置
wx:
  appid: wx6bc272547276f111
  app:
    secret: 5f79f46886133514916393f6e603954d

#excel导表路径
excel:
  download:
    dir: /download/excel/

#快递查询
express:
  query:
    url: http://poll.kuaidi100.com/poll/query.do

#有关物联网配置
device:
  data:
    url: http://iot.klha.net:8080/services/iotDataService?wsdl
    user: tanv
    password: tanv666

reap:
  exchange:
    weigh: 1800
lbs:
  map:
    key:

---
debug: false
server:
  port: 9000
spring:
  profiles: test
  datasource:
    dynamic:
      primary: write
      datasource:
        write:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.220:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
        read:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.220:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
      hikari:
        max-pool-size: 100
        min-idle: 20
        idle-timeout: 1000
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 4000
    lettuce:
      pool:
        min-idle: 20
        max-idle: 120
        max-wait: 2000
  data:
    mongodb:
      database: activity
      host: 192.168.1.220
      port: 27017
      username: activityAdmin
      password: Is&1+KVb[0
#上传host
upload:
  save-path: /pages/upload
  editor:
    host: 192.168.5.220
  host: 192.168.5.220

recharge:
  review:
    phone: 13450184621

---
debug: false
server:
  port: 9000
spring:
  profiles: dev
  datasource:
    dynamic:
      primary: write
      datasource:
        write:
          username: write
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.5.220:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
        read:
          username: write
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.5.220:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
      hikari:
        max-pool-size: 100
        min-idle: 20
        idle-timeout: 1000
  redis:
    host: 192.168.5.220
    port: 6869
    password: AEnz2DF\Od,GWD#C*+
    database: 0
    timeout: 4000
    lettuce:
      pool:
        min-idle: 20
        max-idle: 120
        max-wait: 2000
  data:
    mongodb:
      database: activity
      host: 192.168.5.220
      port: 27017
      username: activityAdmin
      password: Is&1+KVb[0
#上传host
upload:
  save-path: /pages/upload
  editor:
    host: http://192.168.5.220
  host: http://192.168.5.220

swagger:
  enabled: true
  title: moguying-plant
  description: 蘑菇营项目api
  version: 0.0.1-SNAPSHOT
  base-package: com.moguying.plant
  docket:
    frontApi:
      title: 应用接口
      description: 应用接口
      base-path: /api/**
    backEndApi:
      title: 后台管理接口
      description: 后台管理接口
      base-path: /backEnd/**
    paymentApi:
      title: 支付相关接口
      description: 支付相关接口
      base-path: /payment/**
  global-operation-parameters[0]:
    name: Auth-Token
    modelRef: string
    parameterType: header
    require: true

recharge:
  review:
    phone: 13450184621

---
debug: false
server:
  port: 9000
spring:
  profiles: pro-master
  datasource:
    dynamic:
      primary: write
      datasource:
        write:
          username: dbManager
          password: Ld1*7@&13Ai+ab
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.18.146.179:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
        read:
          username: dbManager
          password: Ld1*7@&13Ai+ab
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.18.146.178:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
      hikari:
        max-pool-size: 100
        min-idle: 20
        idle-timeout: 1000
  redis:
    host: 172.18.146.177
    port: 6869
    password: AEnz2DF\Od,GWD#C*+
    database: 0
    timeout: 4000
    lettuce:
      pool:
        min-idle: 20
        max-idle: 120
        max-wait: 2000
  data:
    mongodb:
      host: 172.18.146.177
      port: 27589
      database: activity
      username: activityAdmin
      password: Is&1+KVb[0

#上传host
upload:
  save-path: /pages/upload
  editor:
    host: https://image.zymoguying.com
  host: https://image.zymoguying.com

recharge:
  review:
    phone: 13823239796



---
debug: false
server:
  port: 9000
spring:
  profiles: pro-slave
  datasource:
    dynamic:
      primary: write
      datasource:
        write:
          username: dbManager
          password: Ld1*7@&13Ai+ab
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.18.146.179:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
        read:
          username: dbManager
          password: Ld1*7@&13Ai+ab
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.18.146.178:3306/moguying?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false
      hikari:
        max-pool-size: 100
        min-idle: 20
        idle-timeout: 1000
  redis:
    host: 172.18.146.177
    port: 6869
    password: AEnz2DF\Od,GWD#C*+
    database: 0
    timeout: 4000
    lettuce:
      pool:
        min-idle: 20
        max-idle: 120
        max-wait: 2000
  data:
    mongodb:
      host: 172.18.146.177
      port: 27589
      database: activity
      username: activityAdmin
      password: Is&1+KVb[0

#上传host
upload:
  save-path: /pages/upload
  editor:
    host: https://image.zymoguying.com
  host: https://image.zymoguying.com

recharge:
  review:
    phone: 13823239796
